server.port=8080

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=500MB

spring.application.name=filepacker

app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}